# Generated by Django 2.2.3 on 2019-07-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamXapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allusers',
            name='myskill',
            field=models.ManyToManyField(blank=True, to='TeamXapp.skills'),
        ),
    ]
