# Generated by Django 2.2.2 on 2019-07-11 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamXapp', '0002_allusers_myskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WrkPttrn', models.CharField(max_length=30, verbose_name='Work Pattern:')),
            ],
            options={
                'verbose_name': 'Work Pattern',
                'verbose_name_plural': 'Work Patterns',
            },
        ),
        migrations.AlterField(
            model_name='allusers',
            name='myskill',
            field=models.ManyToManyField(blank=True, to='TeamXapp.skills'),
        ),
        migrations.AddField(
            model_name='allusers',
            name='WorkPattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamXapp.Work_Pattern', verbose_name='Work Pattern: '),
        ),
    ]
