# Generated by Django 2.2.2 on 2019-07-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamXapp', '0003_auto_20190711_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='allusers',
            name='Hours_Per_Week',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Hours Per Week: '),
        ),
        migrations.AlterField(
            model_name='allusers',
            name='myskill',
            field=models.ManyToManyField(blank=True, to='TeamXapp.skills'),
        ),
    ]
