# Generated by Django 2.2.3 on 2019-07-11 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamXapp', '0005_auto_20190711_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmembers',
            name='Hours_Per_Week',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Hours Per Week: '),
        ),
        migrations.AlterField(
            model_name='allmembers',
            name='myskill',
            field=models.ManyToManyField(blank=True, to='TeamXapp.Skills', verbose_name='Skills'),
        ),
        migrations.AlterField(
            model_name='allmembers',
            name='scrumTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamXapp.ScrumTeam', verbose_name='Scrum team: '),
        ),
    ]
