# Generated by Django 2.2.3 on 2019-07-11 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamXapp', '0006_auto_20190711_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrkPttrn', models.CharField(max_length=30, verbose_name='Work Pattern:')),
            ],
            options={
                'verbose_name': 'Work Pattern',
                'verbose_name_plural': 'Work Patterns',
            },
        ),
        migrations.RemoveField(
            model_name='allmembers',
            name='WorkPattern',
        ),
        migrations.AlterField(
            model_name='allmembers',
            name='scrumTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamXapp.ScrumTeam', verbose_name='Scrum team: '),
        ),
        migrations.DeleteModel(
            name='Work_Pattern',
        ),
        migrations.AddField(
            model_name='allmembers',
            name='workpattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamXapp.WorkPattern', verbose_name='Work Pattern: '),
        ),
    ]
