# Generated by Django 2.2.3 on 2019-07-11 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamXapp', '0007_auto_20190711_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allmembers',
            old_name='Hours_Per_Week',
            new_name='hours_per_week',
        ),
        migrations.AlterField(
            model_name='allmembers',
            name='scrumTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamXapp.ScrumTeam', verbose_name='Scrum team: '),
        ),
    ]
