# Generated by Django 2.2.3 on 2019-07-11 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamXapp', '0012_auto_20190711_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrumTeamStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Scrum Team Status',
                'verbose_name_plural': 'Scrum Team Status',
            },
        ),
        migrations.CreateModel(
            name='ScrumTeamType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Scrum Team Type',
                'verbose_name_plural': 'Scrum Team Types',
            },
        ),
        migrations.AlterField(
            model_name='allmembers',
            name='scrumTeam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamXapp.ScrumTeam', verbose_name='Scrum team: '),
        ),
        migrations.AlterField(
            model_name='allmembers',
            name='scrum_team_roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamXapp.ScrumTeamRole', verbose_name='Scrum Team Roles: '),
        ),
        migrations.AddField(
            model_name='scrumteam',
            name='team_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamXapp.ScrumTeamStatus'),
        ),
        migrations.AddField(
            model_name='scrumteam',
            name='team_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamXapp.ScrumTeamType'),
        ),
    ]
