# Generated by Django 2.2.3 on 2019-07-12 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamXapp', '0017_auto_20190712_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allmembers',
            old_name='scrumTeam',
            new_name='scrum_team',
        ),
        migrations.RenameField(
            model_name='allmembers',
            old_name='secondName',
            new_name='second_name',
        ),
        migrations.AlterField(
            model_name='allmembers',
            name='scrum_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamXapp.ScrumTeam', verbose_name='Scrum team: '),
        ),
        migrations.AlterField(
            model_name='allmembers',
            name='scrum_team_roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamXapp.ScrumTeamRole', verbose_name='Scrum Team Roles: '),
        ),
    ]
