# Generated by Django 2.2.3 on 2019-07-12 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamXapp', '0023_auto_20190712_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveEndTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_end_time', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Leave End Time',
            },
        ),
        migrations.CreateModel(
            name='LeaveStartTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_start_time', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Leave Start Time',
            },
        ),
        migrations.AlterField(
            model_name='allmembers',
            name='scrum_team_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamXapp.ScrumTeam', verbose_name='Scrum team: '),
        ),
        migrations.AlterField(
            model_name='allmembers',
            name='scrum_team_roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamXapp.ScrumTeamRole', verbose_name='Scrum Team Roles: '),
        ),
        migrations.AddField(
            model_name='allmembers',
            name='leave_end_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamXapp.LeaveEndTime'),
        ),
        migrations.AddField(
            model_name='allmembers',
            name='leave_start_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamXapp.LeaveStartTime'),
        ),
    ]
