# Generated by Django 2.1.7 on 2019-07-12 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamXapp', '0035_auto_20190712_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allmembers',
            name='leave_end_time',
        ),
        migrations.RemoveField(
            model_name='allmembers',
            name='leave_note',
        ),
        migrations.RemoveField(
            model_name='allmembers',
            name='leave_start_time',
        ),
        migrations.RemoveField(
            model_name='allmembers',
            name='leave_status',
        ),
        migrations.AlterField(
            model_name='allmembers',
            name='scrum_team_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamXapp.ScrumTeam', verbose_name='Scrum team: '),
        ),
        migrations.AlterField(
            model_name='allmembers',
            name='scrum_team_roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamXapp.ScrumTeamRole', verbose_name='Scrum Team Roles: '),
        ),
        migrations.DeleteModel(
            name='LeaveEndTime',
        ),
        migrations.DeleteModel(
            name='LeaveNote',
        ),
        migrations.DeleteModel(
            name='LeaveStartTime',
        ),
    ]
