# Generated by Django 2.1.7 on 2019-07-12 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamXapp', '0036_auto_20190712_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavestatus',
            options={'verbose_name': 'Leave Type', 'verbose_name_plural': 'Leave Type'},
        ),
        migrations.AlterModelOptions(
            name='scrumteamrole',
            options={'verbose_name': 'Job Role', 'verbose_name_plural': 'Job Roles'},
        ),
        migrations.RemoveField(
            model_name='allmembers',
            name='workpattern',
        ),
        migrations.AlterField(
            model_name='allmembers',
            name='scrum_team_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamXapp.ScrumTeam', verbose_name='Scrum team: '),
        ),
        migrations.AlterField(
            model_name='allmembers',
            name='scrum_team_roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamXapp.ScrumTeamRole', verbose_name='Scrum Team Roles: '),
        ),
    ]
