# Generated by Django 2.2.3 on 2019-07-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamXapp', '0034_auto_20190712_1327'),
        ('TeamXapp', '0037_auto_20190712_1327'),
    ]

    operations = [
    ]
