# Generated by Django 2.2.3 on 2019-07-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamXapp', '0040_auto_20190712_1351'),
        ('TeamXapp', '0038_auto_20190712_1058'),
    ]

    operations = [
    ]
