# Generated by Django 2.2.3 on 2019-07-12 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamXapp', '0047_auto_20190712_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmembers',
            name='scrum_team_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamXapp.ScrumTeam', verbose_name='Scrum team: '),
        ),
        migrations.AlterField(
            model_name='allmembers',
            name='scrum_team_roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamXapp.ScrumTeamRole', verbose_name='Scrum Team Roles: '),
        ),
        migrations.AlterField(
            model_name='leavecalendar',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TeamXapp.LeaveStatus'),
        ),
        migrations.AlterField(
            model_name='scrumteam',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TeamXapp.Domain', verbose_name='Domain'),
        ),
        migrations.AlterField(
            model_name='scrumteam',
            name='scrum_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TeamXapp.AllMembers', verbose_name='Scrum Master'),
        ),
        migrations.AlterField(
            model_name='scrumteam',
            name='team_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TeamXapp.ScrumTeamStatus', verbose_name='Team Status'),
        ),
        migrations.AlterField(
            model_name='scrumteam',
            name='team_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TeamXapp.ScrumTeamType', verbose_name='Team Type'),
        ),
    ]
