# Generated by Django 2.2.3 on 2019-07-13 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamXapp', '0048_auto_20190712_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workpattern',
            old_name='wrkPttrn',
            new_name='work_pattern',
        ),
        migrations.RemoveField(
            model_name='scrumteam',
            name='teamName',
        ),
        migrations.AddField(
            model_name='allmembers',
            name='work_pattern',
            field=models.CharField(blank=True, choices=[('F', 'FULL TIME'), ('P', 'PART TIME'), ('C', 'COMPRESSED HOURS')], default='F', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='scrumteam',
            name='team_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Scrum Team Name'),
        ),
        migrations.AlterField(
            model_name='allmembers',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='allmembers',
            name='hours_per_week',
            field=models.IntegerField(default=35, verbose_name='Hours Per Week'),
        ),
        migrations.AlterField(
            model_name='allmembers',
            name='scrum_team_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamXapp.ScrumTeam', verbose_name='Scrum team'),
        ),
        migrations.AlterField(
            model_name='allmembers',
            name='scrum_team_roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TeamXapp.ScrumTeamRole', verbose_name='Roles'),
        ),
        migrations.AlterField(
            model_name='allmembers',
            name='second_name',
            field=models.CharField(max_length=30, verbose_name='Second name'),
        ),
    ]
