# Generated by Django 2.2.3 on 2019-07-16 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamXapp', '0063_auto_20190715_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmembers',
            name='in_team',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='allmembers',
            name='scrum_team_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='TeamXapp.ScrumTeam', verbose_name='Scrum team'),
        ),
        migrations.AlterField(
            model_name='allmembers',
            name='scrum_team_roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TeamXapp.ScrumTeamRole', verbose_name='Roles'),
        ),
        migrations.AlterField(
            model_name='allmembers',
            name='work_pattern',
            field=models.CharField(blank=True, choices=[('FULL TIME', 'FULL TIME'), ('PART TIME', 'PART TIME'), ('COMPRESSED HOURS', 'COMPRESSED HOURS')], default='FULL TIME', max_length=16, null=True),
        ),
    ]
