# Generated by Django 2.2.3 on 2019-07-17 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeamXapp', '0067_auto_20190717_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavecalendar',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Leave Note'),
        ),
        migrations.AlterField(
            model_name='allmembers',
            name='scrum_team_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='TeamXapp.ScrumTeam', verbose_name='Scrum teams'),
        ),
        migrations.AlterField(
            model_name='allmembers',
            name='scrum_team_roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TeamXapp.ScrumTeamRole', verbose_name='Roles'),
        ),
    ]
