# Generated by Django 2.2.3 on 2019-07-17 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamXapp', '0063_auto_20190715_1308'),
        ('TeamXapp', '0068_auto_20190717_0813'),
    ]

    operations = [
    ]
