# Generated by Django 2.2.3 on 2019-07-17 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamXapp', '0069_merge_20190717_0932'),
        ('TeamXapp', '0073_auto_20190717_0842'),
    ]

    operations = [
    ]
