# Generated by Django 2.2.3 on 2019-07-18 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamXapp', '0070_auto_20190717_0959'),
        ('TeamXapp', '0075_auto_20190717_1029'),
    ]

    operations = [
    ]
